oc_louvre_index:
    path:     /
    defaults: { _controller: OCLouvreBundle:View:index }
    methods: [GET]

oc_louvre_date:
    path:     /date
    defaults: { _controller: OCLouvreBundle:Louvre:date }

oc_louvre_commande:
    path:     /commande
    defaults: { _controller: OCLouvreBundle:Louvre:commande }

oc_louvre_prix:
    path:     /prix
    defaults: { _controller: OCLouvreBundle:Louvre:prix }
    methods: [GET]

oc_louvre_resume:
    path:     /resume
    defaults: { _controller: OCLouvreBundle:View:resume }
    methods: [GET]

oc_louvre_payment:
    path:     /payment
    defaults: { _controller: OCLouvreBundle:Louvre:payment }

oc_louvre_confirm:
    path:     /confirm
    defaults: { _controller: OCLouvreBundle:Louvre:confirm }

oc_louvre_mail:
    path:     /mail
    defaults: { _controller: OCLouvreBundle:Mail:mail }
    methods: [GET]

oc_louvre_done:
    path:     /done
    defaults: { _controller: OCLouvreBundle:Mail:done }
    methods: [GET]

oc_louvre_fail:
    path:     /fail
    defaults: { _controller: OCLouvreBundle:View:fail }
    methods: [GET]

oc_louvre_error:
    path:     /error
    defaults: { _controller: OCLouvreBundle:View:error }
    methods: [GET]

oc_louvre_ajaxNumber:
    path:     /ajax/number/{date}/{number}
    defaults: { _controller: OCLouvreBundle:Ajax:ajaxNumber }
    methods: [POST]





#oc_louvre_resume:
#    path:     /resume/{id}
#    defaults:
#        _controller: OCLouvreBundle:Louvre:resume
#    requirements:
#        id: \d+


#oc_louvre_ getAjaxNumber:
#    path:     get/ajax/number/{date}/{number}
#    defaults: { _controller: OCLouvreBundle:Ajax:getAjaxNumber }
#    methods: [POST]
#    methods: [GET]














