services:
#    oc_louvre.services:
#        class: OC\LouvreBundle\Services\GetCheck
#        arguments: [ "@doctrine.orm.entity_manager",  "@service_container" ] 

#    oc_louvre.example:
#        class: OC\LouvreBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

