<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSvm4rmd\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSvm4rmd/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerSvm4rmd.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerSvm4rmd\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerSvm4rmd\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Svm4rmd',
    'container.build_id' => 'aa145b1d',
    'container.build_time' => 1517587199,
));
